//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.IO;

namespace EngSchool_Shamilova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int ManufacturerID { get; set; }
        public bool IsActive { get; set; }
        public decimal Price { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }

        // Возвращает абсолютный путь к изображению.
        public string GetPhoto
        {
            get
            {
                if (Image is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\" + Image.Trim();
            }
        }

        // Задаёт цвет фона товара.
        public string GetColor
        {
            get
            {
                if (IsActive)
                    return "#fff";
                else
                    return "#8C8181";
            }
        }

        // Текстовое представление активности товара.
        public string GetStatus
        {
            get
            {
                if (IsActive)
                    return "";
                else
                    return "нет в наличии";
            }
        }

        public string GetInfo
        {
            get
            {
                return $"{Name} - {Price.ToString("c")} рублей.";
            }
        }
    }
}
